export type Project = {
  name: string
  description: string
  github: string
  link?: string
  linkTitle?: string
}

export const projects = [
  {
    name: "Stacks",
    description: "A catalog of web dev stacks generated by users.",
    github: "https://github.com/azbauer8/Stacks",
    link: "https://stacks.byzach.dev",
    linkTitle: "stacks.byzach.dev",
  },
  {
    name: "Scrumble",
    description:
      "A simple cross-platform WYSIWYG Markdown editor. Built with Tauri, React, Remirror, and ShadCN UI.",
    github: "https://github.com/azbauer8/Scrumble",
  },
  {
    name: "Games Radar",
    description:
      "A micro-service site showing recent game releases fetched from rawg's api (also loosely cloned their layout).",
    github: "https://github.com/azbauer8/Games",
    link: "https://games.byzach.dev",
    linkTitle: "games.byzach.dev",
  },
  {
    name: "Dotfiles",
    description:
      "A collection of configuration files I've tweaked for a variety of tools I use on Windows and Mac.",
    github: "https://github.com/azbauer8/Dotfiles",
    link: "https://github.com/azbauer8/Dotfiles/wiki",
    linkTitle: "Wiki",
  },
]
